export const countries = [
    {"name": "Afghanistan"},
    {"name": "Albania"},
    {"name": "Algeria"},
    {"name": "Andorra"},
    {"name": "Angola"},
    {"name": "Anguilla"},
    {"name": "Antarctica"},
    {"name": "Antigua and Barbuda"},
    {"name": "Argentina"},
    {"name": "Armenia"},
    {"name": "Aruba"},
    {"name": "Australia"},
    {"name": "Austria"},
    {"name": "Azerbaijan"},
    {"name": "Bahamas",},
    {"name": "Bahrain"},
    {"name": "Bangladesh"},
    {"name": "Barbados"},
    {"name": "Belarus"},
    {"name": "Belgium"},
    {"name": "Belize"},
    {"name": "Benin"},
    {"name": "Bermuda"},
    {"name": "Bhutan"},
    {"name": "Bolivia"},
    {"name": "Bosnia and Herzegovina"},
    {"name": "Botswana"},
    {"name": "Brazil"},
    {"name": "Brunei"},
    {"name": "Bulgaria"},
    {"name": "Burkina Faso"},
    {"name": "Burundi"},
    {"name": "Cambodia"},
    {"name": "Cameroon"},
    {"name": "Canada"},
    {"name": "Cape Verde"},
    {"name": "Cayman Islands"},
    {"name": "Central African Republic"},
    {"name": "Chad"},
    {"name": "Chile"},
    {"name": "China"},
    {"name": "Christmas Island"},
    {"name": "Colombia"},
    {"name": "Comoros"},
    {"name": "Congo"},
    {"name": "Cook Islands"},
    {"name": "Costa Rica"},
    {"name": "Croatia"},
    {"name": "Cuba"},
    {"name": "Cyprus"},
    {"name": "Czech Republic"},
    {"name": "Denmark"},
    {"name": "Djibouti"},
    {"name": "Dominican Republic"},
    {"name": "Ecuador"},
    {"name": "Egypt"},
    {"name": "El Salvador"},
    {"name": "Equatorial Guinea"},
    {"name": "Eritrea"},
    {"name": "Estonia"},
    {"name": "Ethiopia"},
    {"name": "Faroe Islands"},
    {"name": "Fiji"},
    {"name": "Finland"},
    {"name": "France"},
    {"name": "French Guiana"},
    {"name": "French Polynesia"},
    {"name": "Gabon"},
    {"name": "Gambia"},
    {"name": "Georgia"},
    {"name": "Germany"},
    {"name": "Ghana"},
    {"name": "Gibraltar"},
    {"name": "Greece"},
    {"name": "Greenland"},
    {"name": "Grenada"},
    {"name": "Guadeloupe"},
    {"name": "Guam"},
    {"name": "Guatemala"},
    {"name": "Guinea"},
    {"name": "Guinea-Bissau"},
    {"name": "Guyana"},
    {"name": "Haiti"},
    {"name": "Holy See (Vatican City State)"},
    {"name": "Honduras"},
    {"name": "Hong Kong"},
    {"name": "Hungary"},
    {"name": "Iceland"},
    {"name": "India"},
    {"name": "Indonesia"},
    {"name": "Iran"},
    {"name": "Iraq"},
    {"name": "Ireland"},
    {"name": "Israel"},
    {"name": "Italy"},
    {"name": "Jamaica"},
    {"name": "Japan"},
    {"name": "Jordan"},
    {"name": "Kazakhstan"},
    {"name": "Kenya"},
    {"name": "Kiribati"},
    {"name": "North Korea"},
    {"name": "South Korea"},
    {"name": "Kuwait"},
    {"name": "Kyrgyzstan"},
    {"name": "Laos"},
    {"name": "Latvia"},
    {"name": "Lebanon"},
    {"name": "Lesotho"},
    {"name": "Liberia"},
    {"name": "Libya "},
    {"name": "Liechtenstein"},
    {"name": "Lithuania"},
    {"name": "Luxembourg"},
    {"name": "Macao"},
    {"name": "North Macedonia"},
    {"name": "Madagascar"},
    {"name": "Malawi"},
    {"name": "Malaysia"},
    {"name": "Maldives"},
    {"name": "Mali"},
    {"name": "Malta"},
    {"name": "Marshall Islands"},
    {"name": "Martinique"},
    {"name": "Mauritania"},
    {"name": "Mauritius"},
    {"name": "Mexico"},
    {"name": "Micronesia"},
    {"name": "Moldova"},
    {"name": "Monaco"},
    {"name": "Mongolia"},
    {"name": "Morocco"},
    {"name": "Mozambique"},
    {"name": "Myanmar"},
    {"name": "Namibia"},
    {"name": "Nauru"},
    {"name": "Nepal"},
    {"name": "Netherlands"},
    {"name": "New Zealand"},
    {"name": "Nicaragua"},
    {"name": "Niger"},
    {"name": "Nigeria"},
    {"name": "Norway"},
    {"name": "Oman"},
    {"name": "Pakistan"},
    {"name": "Palau"},
    {"name": "Palestinian Territory"},
    {"name": "Panama"},
    {"name": "Papua New Guinea"},
    {"name": "Paraguay"},
    {"name": "Peru"},
    {"name": "Philippines"},
    {"name": "Poland"},
    {"name": "Portugal"},
    {"name": "Puerto Rico"},
    {"name": "Qatar"},
    {"name": "Reunion"},
    {"name": "Romania"},
    {"name": "Russia"},
    {"name": "Rwanda"},
    {"name": "Saint Helena"},
    {"name": "Saint Kitts and Nevis"},
    {"name": "Saint Lucia"},
    {"name": "Saint Pierre and Miquelon"},
    {"name": "Saint Vincent and the Grenadines"},
    {"name": "Samoa"},
    {"name": "San Marino"},
    {"name": "Saudi Arabia"},
    {"name": "Senegal"},
    {"name": "Serbia"},
    {"name": "Montenegro"},
    {"name": "Seychelles"},
    {"name": "Sierra Leone"},
    {"name": "Singapore"},
    {"name": "Slovakia"},
    {"name": "Slovenia"},
    {"name": "Solomon Islands"},
    {"name": "Somalia"},
    {"name": "South Africa"},
    {"name": "Spain"},
    {"name": "Sri Lanka"},
    {"name": "Sudan"},
    {"name": "Suriname"},
    {"name": "Swaziland"},
    {"name": "Sweden"},
    {"name": "Switzerland"},
    {"name": "Syria"},
    {"name": "Taiwan"},
    {"name": "Tajikistan"},
    {"name": "Tanzania"},
    {"name": "Thailand"},
    {"name": "Timor-Leste"},
    {"name": "Togo"},
    {"name": "Tonga"},
    {"name": "Trinidad and Tobago"},
    {"name": "Tunisia"},
    {"name": "Turkey"},
    {"name": "Turkmenistan"},
    {"name": "Tuvalu"},
    {"name": "Uganda"},
    {"name": "Ukraine"},
    {"name": "United Arab Emirates"},
    {"name": "United Kingdom"},
    {"name": "United States"},
    {"name": "Uruguay"},
    {"name": "Uzbekistan"},
    {"name": "Vanuatu"},
    {"name": "Venezuela"},
    {"name": "Vietnam"},
    {"name": "Western Sahara"},
    {"name": "Yemen"},
    {"name": "Zambia"},
    {"name": "Zimbabwe"}
    ]
    